import test from 'node:test';import assert from 'node:assert/strict';
import {createCycleMap,A1_CAMPAIGN_CYCLES as cycles} from '../packages/campaign/a1/cycle-map.mjs';import {createCampaignDefinition} from '../packages/campaign/a1/campaign-definition.mjs';import {createCampaignJournal} from '../packages/campaign/a1/campaign-journal.mjs';import {projectCampaign} from '../packages/campaign/a1/campaign-projection.mjs';import {hashCampaignDefinition,hashCampaignProjection} from '../packages/campaign/a1/campaign-serialization.mjs';import {createInMemoryCampaignStore} from '../packages/campaign/a1/campaign-store-contract.mjs';import {resumeCampaign} from '../packages/campaign/a1/campaign-runtime.mjs';
import {A1_CURRICULUM} from '../packages/curriculum/a1/curriculum.mjs';import {A1_SEMANTIC_CURRICULUM} from '../packages/curriculum/a1/semantic-curriculum.mjs';import {createA1SemanticView} from '../packages/curriculum/a1/semantic-view.mjs';import {A1_EXISTING_TARGET,mapExistingRealizations} from '../packages/curriculum/a1/existing-realizations.mjs';import {getLanguagePack} from '../packages/language-packs/catalog.mjs';import {A1_DEFAULT_MISSION_BLUEPRINT as blueprint} from '../packages/experience/a1/default-mission-blueprint.mjs';import {A1_DEFAULT_ADAPTIVE_POLICY as policy} from '../packages/adaptive/a1/policy.mjs';import {hashMission} from '../packages/experience/a1/mission-serialization.mjs';import {hashAdaptiveSelection} from '../packages/adaptive/a1/adaptive-serialization.mjs';import {selectNextMission} from '../packages/adaptive/a1/adaptive-planner.mjs';
const t=A1_EXISTING_TARGET, b='MC-A1-002', c='MC-A1-003';
const map=createCycleMap({id:'release-map',version:'1',cycles,participations:[{targetId:t,cycle:'CONTACT',role:'INTRODUCE'},{targetId:t,cycle:'REFERENCE',role:'REINFORCE'},{targetId:b,cycle:'ACTION',role:'APPLY'},{targetId:c,cycle:'CONTEXT',role:'CHECKPOINT'}]});
const definition=createCampaignDefinition({id:'release-campaign',version:'1.5',cycleMap:map,nodes:[{id:'n1',targetId:t,cycle:'CONTACT',role:'INTRODUCE'},{id:'n2',targetId:b,cycle:'ACTION',role:'APPLY'},{id:'n3',targetId:c,cycle:'CONTEXT',role:'CHECKPOINT'}],edges:[{from:'n1',to:'n2'},{from:'n1',to:'n3'}],gates:[{id:'g2',nodeId:'n2',requirements:[{kind:'ACCEPTED_EVIDENCE',targetId:t}]},{id:'g3',nodeId:'n3',requirements:[{kind:'ACCEPTED_EVIDENCE',targetId:t},{kind:'APPLY',targetId:b}]}]});
const event=(id,cursor,type,targetId,extra={})=>({id,cursor,campaignId:definition.id,definitionVersion:definition.version,type,targetId,at:'2026-09-24T10:00:00-03:00',...extra});
const journal=events=>createCampaignJournal({campaignId:definition.id,definitionVersion:definition.version,events});
const asOf='2026-09-24T12:00:00-03:00';
test('legal route changes only after explicit evidence and APPLY events',()=>{const p0=projectCampaign({definition,journal:journal([]),asOf});assert.deepEqual(p0.availableTargetIds,[t]);const p1=projectCampaign({definition,journal:journal([event('e1',1,'EVIDENCE',t,{accepted:true})]),asOf});assert.ok(p1.availableTargetIds.includes(b));assert.ok(!p1.availableTargetIds.includes(c));const p2=projectCampaign({definition,journal:journal([event('e1',1,'EVIDENCE',t,{accepted:true}),event('e2',2,'APPLY',b,{accepted:true})]),asOf});assert.ok(p2.availableTargetIds.includes(c));});

test('discarded projection and stale cache reconstruct byte-identically from Journal',()=>{const events=[event('e1',1,'EVIDENCE',t,{accepted:true})];const j=journal(events);const p=projectCampaign({definition,journal:j,asOf});const hash=hashCampaignProjection(p);const store=createInMemoryCampaignStore();store.appendEvents({campaignId:definition.id,definitionVersion:definition.version,events});store.saveSnapshotCache({campaignId:definition.id,definitionVersion:definition.version,snapshot:{hash:'stale'}});const replay=store.verifyReplay({campaignId:definition.id,definitionVersion:definition.version,replay:fresh=>{const projection=projectCampaign({definition,journal:fresh,asOf});return{projection,hash:hashCampaignProjection(projection)}}});assert.equal(replay.status,'CACHE_STALE');assert.equal(replay.authority,'JOURNAL_REPLAY');assert.equal(replay.hash,hash);assert.deepEqual(replay.projection,p);});

test('V1.1 V1.2 HNK Esperanto V1.3 and V1.4 locks survive V1.5',()=>{const caps=A1_CURRICULUM.families.flatMap(f=>f.capabilities),sem=A1_SEMANTIC_CURRICULUM.families.flatMap(f=>f.capabilities);assert.deepEqual([A1_CURRICULUM.families.length,caps.length,caps.flatMap(x=>x.microCapabilities).length,A1_CURRICULUM.cycles.length],[12,60,180,7]);assert.deepEqual([A1_SEMANTIC_CURRICULUM.families.length,sem.length,sem.flatMap(x=>x.contracts).length],[12,60,180]);const view=createA1SemanticView(A1_CURRICULUM,A1_SEMANTIC_CURRICULUM),cell={microCapabilityId:t,linguistic:'READY',representation:{PRIMARY_TEXT:'READY'},pedagogical:'READY',evidence:'READY'},base=id=>({definition,journal:journal([]),asOf,semanticView:view,events:[],readinessCells:[cell],languagePack:mapExistingRealizations(getLanguagePack(id)),blueprint,policy,versionVector:{structural:'1.1',semantic:'1.2',experience:'1.3',adaptive:'1.4',campaign:'1.5'}});const h=resumeCampaign(base('hnk'));assert.equal(h.nextMission.steps[0].realizations[0].bundle.primary.value,'EN ZAMI HNK KE');assert.equal(hashMission(h.nextMission),'9e7435cf4ccf1d12d2c99e58e12ecf7a91cc7b4bf594c38665a069d1f24922fc');const v14=selectNextMission({semanticView:view,targetIds:[t],events:[],readinessCells:[cell],languagePack:mapExistingRealizations(getLanguagePack('hnk')),blueprint,policy,versionVector:{structural:'1.1',semantic:'1.2',experience:'1.3',adaptive:'1.4'}});assert.equal(hashAdaptiveSelection(v14),'4344f0987798182c742732d2481ae986926cb7e46a36728a7f8750cf506a3690');const e=resumeCampaign(base('esperanto'));assert.equal(e.status,'NO_ELIGIBLE_MISSION');assert.doesNotMatch(JSON.stringify(e),/bundle|primary|EN ZAMI/i);});

test('V1.5 definition and projection hashes are deterministic',()=>{assert.equal(hashCampaignDefinition(definition),hashCampaignDefinition(structuredClone(definition)));const p=projectCampaign({definition,journal:journal([]),asOf});assert.equal(hashCampaignProjection(p),hashCampaignProjection(structuredClone(p)));});
