import test from 'node:test';
import assert from 'node:assert/strict';
import {resumeCampaign} from '../packages/campaign/a1/campaign-runtime.mjs';
import {createCycleMap,A1_CAMPAIGN_CYCLES as cycles} from '../packages/campaign/a1/cycle-map.mjs';
import {createCampaignDefinition} from '../packages/campaign/a1/campaign-definition.mjs';
import {createCampaignJournal} from '../packages/campaign/a1/campaign-journal.mjs';
import {A1_CURRICULUM} from '../packages/curriculum/a1/curriculum.mjs';
import {A1_SEMANTIC_CURRICULUM} from '../packages/curriculum/a1/semantic-curriculum.mjs';
import {createA1SemanticView} from '../packages/curriculum/a1/semantic-view.mjs';
import {A1_EXISTING_TARGET,mapExistingRealizations} from '../packages/curriculum/a1/existing-realizations.mjs';
import {getLanguagePack} from '../packages/language-packs/catalog.mjs';
import {A1_DEFAULT_MISSION_BLUEPRINT as blueprint} from '../packages/experience/a1/default-mission-blueprint.mjs';
import {A1_DEFAULT_ADAPTIVE_POLICY as policy} from '../packages/adaptive/a1/policy.mjs';
const view=createA1SemanticView(A1_CURRICULUM,A1_SEMANTIC_CURRICULUM);
const other='MC-A1-002';
const map=createCycleMap({id:'runtime-map',version:'1',cycles,participations:[{targetId:A1_EXISTING_TARGET,cycle:'CONTACT',role:'INTRODUCE'},{targetId:other,cycle:'REFERENCE',role:'APPLY'}]});
const definition=createCampaignDefinition({id:'runtime-campaign',version:'1.5',cycleMap:map,nodes:[{id:'n1',targetId:A1_EXISTING_TARGET,cycle:'CONTACT',role:'INTRODUCE'},{id:'n2',targetId:other,cycle:'REFERENCE',role:'APPLY'}],edges:[{from:'n1',to:'n2'}],gates:[{id:'g2',nodeId:'n2',requirements:[{kind:'ACCEPTED_EVIDENCE',targetId:A1_EXISTING_TARGET}]}]});
const journal=createCampaignJournal({campaignId:'runtime-campaign',definitionVersion:'1.5',events:[]});
const cell={microCapabilityId:A1_EXISTING_TARGET,linguistic:'READY',representation:{PRIMARY_TEXT:'READY'},pedagogical:'READY',evidence:'READY'};
const base=languageId=>({definition,journal,asOf:'2026-09-24T12:00:00-03:00',semanticView:view,events:[],readinessCells:[cell],languagePack:mapExistingRealizations(getLanguagePack(languageId)),blueprint,policy,versionVector:{structural:'1.1',semantic:'1.2',experience:'1.3',adaptive:'1.4',campaign:'1.5'}});
test('projection scopes V1.4 to graph-legal targets and HNK selects a legal READY mission',()=>{const r=resumeCampaign(base('hnk'));assert.equal(r.status,'SELECTED');assert.deepEqual(r.projection.availableTargetIds,[A1_EXISTING_TARGET]);assert.equal(r.nextMission.targetMicroCapabilityIds[0],A1_EXISTING_TARGET);assert.equal(r.why.adaptive.signal,'NEW');});
test('open graph cannot bypass Esperanto linguistic block or leak payload',()=>{const r=resumeCampaign(base('esperanto'));assert.equal(r.status,'NO_ELIGIBLE_MISSION');assert.equal(r.nextMission,null);assert.ok(r.why.blockingReasons.length);assert.doesNotMatch(JSON.stringify(r),/bundle|primary|EN ZAMI/i);});
test('Why trace exposes graph prerequisites, gates, evidence ids, adaptive signal and provenance',()=>{const r=resumeCampaign(base('hnk'));assert.deepEqual(r.why.nodes.n1.prerequisites,[]);assert.deepEqual(r.why.nodes.n2.prerequisites,['n1']);assert.equal(r.why.gates.g2.status,'UNSATISFIED');assert.deepEqual(r.why.gates.g2.requirements[0].eventIds,[]);assert.equal(r.why.adaptive.signal,'NEW');assert.deepEqual(r.why.versions,{campaign:'1.5',definition:'1.5',cycleMap:'1',structural:'1.1',semantic:'1.2',experience:'1.3',adaptive:'1.4'});});
